import "@/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";

import { Layout } from "@/components/site/layout";
import { TRPCReactProvider } from "@/trpc/react";
import { ConvexClientProvider } from "@/components/ConvexClientProvider";

export const metadata: Metadata = {
  title: "EHS Thunderbolt",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/CheyenneEast.png" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang='en'
      className={`${geist.variable} dark`}
    >
      <body className='h-dvh w-dvw overflow-y-scroll'>
        <ConvexClientProvider>
          <TRPCReactProvider>
            <Layout>{children}</Layout>
          </TRPCReactProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
